const amazonCategories = [
  "All Departments",
  "Alexa Skills",
  "Amazon Devices",
  "Amazon Fresh",
  "Amazon Pharmacy",
  "Amazon Warehouse",
  "Appliances",
  "Apps & Games",
  "Arts, Crafts & Sewing",
  "Audible Books & Originals",
  "Automotive Parts & Accessories",
  "Baby",
  "Beauty & Personal Care",
  "Books",
  "CDs & Vinyl",
  "Cell Phones & Accessories",
  "Clothing, Shoes & Jewelry",
  "Collectibles & Fine Art",
  "Computers",
  "Credit and Payment Cards",
  "Digital Educational Resources",
  "Digital Music",
  "Electronics",
  "Garden & Outdoor",
  "Gift Cards",
  "Grocery & Gourmet Food",
  "Handmade",
  "Health & Household",
  "Home & Business Services",
  "Home & Kitchen",
  "Industrial & Scientific",
  "Just for Prime",
  "Kindle Store",
  "Luggage & Travel Gear",
  "Luxury Stores",
  "Magazine Subscriptions",
  "Movies & TV",
  "Musical Instruments",
  "Office Products",
  "Pet Supplies",
  "Premium Beauty",
  "Prime Video",
  "Smart Home",
  "Software",
  "Sports & Outdoors",
  "Subscribe & Save",
  "Tools & Home Improvement",
  "Toys & Games",
  "Video Games"
];
